version: '3.7'
services:
  deno_app:
    build:
      context: .
      dockerfile: Dockerfile
  ports:
    - '1234:80'
  restart: always

tunnel:
  container_name: cloudflared-tunnel
  image: cloudflare/cloudflared
  restart: unless-stopped
  command: tunnel run
  environment:
    - TUNNEL_TOKEN=${TUNNEL_TOKEN}
