version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      custom_net:
        ipv4_address: 10.0.1.99

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1
